<h1>Victuz Machine learning PI6</h1>

In [ ]:
import pandas as pd

eventdf = pd.read_csv("evenementinformatie.csv",sep=';')
berichtdf = pd.read_csv("berichtinteracties_met_sentiment.csv",sep=';')
evenentuserdf = pd.read_csv("evenementaanwezigheid.csv",sep=';')
userdf = pd.read_csv("gebruikersinformatie.csv",sep=';')

In [10]:
objs = [berichtdf, userdf]


df = pd.concat(objs, axis=0) #mergen van users en userberichten

In [11]:
df

,BerichtID,BerichtDatum,GebruikerID,EvenementID,BerichtSentiment,OntvangenLikes,OntvangenReacties,RegistratieDatum,LaatsteLogin,Leeftijd,Studierichting,Studiejaar,Lidmaatschapstype
0,B001,18-5-2023,G309,E012,Neutraal,5.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
1,B002,6-10-2023,G021,E039,Positief,9.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN
2,B003,7-7-2023,G111,E001,Positief,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
3,B004,5-10-2023,G168,E015,Negatief,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,B005,22-1-2023,G076,E017,Neutraal,1.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,NaN,NaN,G316,NaN,NaN,NaN,NaN,22-4-2023,17-12-2023,17.0,Data Engineering,Tweedejaars,Regulier
316,NaN,NaN,G317,NaN,NaN,NaN,NaN,30-1-2023,5-4-2023,23.0,Data engineering,Vierdejaars,Regulier
317,NaN,NaN,G318,NaN,NaN,NaN,NaN,24-10-2023,23-7-2024,NaN,Data engineering,Derdejaars,Premium
318,NaN,NaN,G319,NaN,NaN,NaN,NaN,5-10-2023,18-10-2023,23.0,Human computer interaction,Derdejaars,Premium
319,NaN,NaN,G320,NaN,NaN,NaN,NaN,1-2-2023,21-8-2023,19.0,Human computer interaction,Eerstejaars,Premium